apiVersion: v1 #String
kind: Pod #String
metadata: #Dictionary
    name: result-app-pod
    labels: #Dictionary within the metadata dictionary
       app: demo-voting-app
       name: result-app-pod

spec:
       containers: #List/Array
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
          - containerPort: 80


