apiVersion: v1 #String
kind: Pod #String
metadata: #Dictionary
    name: voting-app-pod
    labels: #Dictionary within the metadata dictionary
       app: demo-voting-app
       name: voting-app-pod

spec:
       containers: #List/Array
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
          - containerPort: 80


